//! Deterministic lockfile (ADR-0026 §C "Lockfile determinism strategy",
//! §"Lockfile schema (binding)").
//!
//! The lockfile is the canonical "frozen dep graph" artifact. The
//! constitution `CLAUDE.md` §2.4 binds:
//!
//! > **Deterministic build IDs**: hash of source + toolchain + LLM router
//! > decisions, so any translation is reproducible bit-for-bit given
//! > the same inputs.
//!
//! Same `(manifest, registry-state)` MUST emit byte-identical lockfile
//! bytes. We achieve this by:
//!
//! 1. BTreeMap-backed everything (Rust's BTreeMap iteration is sorted by
//!    key; HashMap's is not).
//! 2. Sorted `[[package]]` entries by `(name, version)`.
//! 3. Sorted `dependencies = [...]` arrays.
//! 4. Hand-written canonical TOML serializer (the `toml` crate's default
//!    serializer doesn't guarantee key ordering across versions).
//! 5. LF-only line endings; trailing newline.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use crate::error::{LockfileError, PkgError};
use crate::manifest::Manifest;
use crate::resolver::{Resolution, ResolvedPackage};

/// Top-level lockfile struct.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Lockfile {
    pub metadata: LockfileMetadata,
    /// Sorted by `(name, version)` ASCII-lex.
    pub packages: Vec<LockfilePackage>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct LockfileMetadata {
    pub manifest_hash: String,
    pub lockfile_version: u32,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct LockfilePackage {
    pub name: String,
    pub version: String,
    pub source: String,
    pub hash: String,
    /// `provenance_hash` from translated crate's `PROVENANCE.toml` if
    /// present (ADR-0007 chain-of-custody).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provenance_hash: Option<String>,
    /// Direct deps as `"name version"` strings, sorted lex.
    #[serde(default)]
    pub dependencies: Vec<String>,
}

/// The on-disk schema version. Bump on any format change that affects
/// determinism (new fields, new sort keys, etc.).
pub const LOCKFILE_VERSION: u32 = 1;

impl Lockfile {
    /// Build a lockfile from a [`Resolution`] + the source [`Manifest`].
    pub fn from_resolution(manifest: &Manifest, resolution: &Resolution) -> Result<Self, PkgError> {
        let manifest_hash = manifest.manifest_hash();

        let mut packages = Vec::new();

        // Root entry comes first (after sort it'll be wherever its
        // (name, version) lands — that's intentional: the lockfile
        // doesn't privilege the root).
        let root_pkg = lock_pkg_from_resolved(&resolution.root);
        packages.push(root_pkg);

        for resolved in resolution.packages.values() {
            packages.push(lock_pkg_from_resolved(resolved));
        }

        // Sort by (name, version).
        packages.sort_by(|a, b| {
            (a.name.as_str(), a.version.as_str()).cmp(&(b.name.as_str(), b.version.as_str()))
        });

        Ok(Self {
            metadata: LockfileMetadata {
                manifest_hash,
                lockfile_version: LOCKFILE_VERSION,
            },
            packages,
        })
    }

    /// Serialize to canonical TOML bytes. Same input → byte-identical bytes.
    /// LF-only line endings, trailing newline.
    #[must_use]
    pub fn to_canonical_toml(&self) -> String {
        let mut out = String::new();

        out.push_str("# cobrust.lock — auto-generated by `cobrust build`. Do not edit.\n");
        out.push_str("# Determinism contract: ADR-0026 §C.\n\n");

        out.push_str("[metadata]\n");
        out.push_str(&format!(
            "manifest_hash = \"{}\"\n",
            self.metadata.manifest_hash
        ));
        out.push_str(&format!(
            "lockfile_version = {}\n",
            self.metadata.lockfile_version
        ));

        // Packages: sorted by (name, version) — the constructor enforces.
        for pkg in &self.packages {
            out.push_str("\n[[package]]\n");
            out.push_str(&format!("name = \"{}\"\n", escape_str(&pkg.name)));
            out.push_str(&format!("version = \"{}\"\n", escape_str(&pkg.version)));
            out.push_str(&format!("source = \"{}\"\n", escape_str(&pkg.source)));
            out.push_str(&format!("hash = \"{}\"\n", escape_str(&pkg.hash)));
            if let Some(ph) = &pkg.provenance_hash {
                out.push_str(&format!("provenance_hash = \"{}\"\n", escape_str(ph)));
            }
            // dependencies list — already sorted by the constructor; we
            // re-sort defensively to honor the determinism contract even
            // if the caller mutated.
            let mut deps = pkg.dependencies.clone();
            deps.sort();
            out.push_str("dependencies = [");
            let mut first = true;
            for d in deps {
                if !first {
                    out.push_str(", ");
                }
                first = false;
                out.push_str(&format!("\"{}\"", escape_str(&d)));
            }
            out.push_str("]\n");
        }

        out
    }

    /// Parse a lockfile from canonical TOML.
    pub fn parse_str(contents: &str) -> Result<Self, PkgError> {
        let raw: RawLockfile =
            toml::from_str(contents).map_err(|e| LockfileError::TomlParse(format!("{e}")))?;
        if raw.metadata.lockfile_version != LOCKFILE_VERSION {
            return Err(PkgError::Lockfile(LockfileError::IncompatibleVersion {
                have: raw.metadata.lockfile_version,
                want: LOCKFILE_VERSION,
            }));
        }
        let mut packages = raw.package.unwrap_or_default();
        packages.sort_by(|a, b| {
            (a.name.as_str(), a.version.as_str()).cmp(&(b.name.as_str(), b.version.as_str()))
        });
        Ok(Self {
            metadata: raw.metadata,
            packages,
        })
    }

    /// Verify the lockfile's `manifest_hash` matches `manifest`. Used to
    /// detect "the manifest changed since this lockfile was emitted".
    pub fn verify_manifest_hash(&self, manifest: &Manifest) -> Result<(), PkgError> {
        let computed = manifest.manifest_hash();
        if computed == self.metadata.manifest_hash {
            Ok(())
        } else {
            Err(PkgError::Lockfile(LockfileError::ManifestHashMismatch {
                recorded: self.metadata.manifest_hash.clone(),
                computed,
            }))
        }
    }
}

#[derive(Deserialize)]
struct RawLockfile {
    metadata: LockfileMetadata,
    #[serde(default)]
    package: Option<Vec<LockfilePackage>>,
}

fn lock_pkg_from_resolved(p: &ResolvedPackage) -> LockfilePackage {
    let mut deps_with_versions: Vec<String> = p.dependency_names.clone();
    // We don't yet know the resolved version of each direct dep here.
    // The lockfile-package transform happens at the resolver level —
    // dep_names are *names* only; turning them into "name version"
    // strings is the lockfile job. We do that in `Lockfile::from_resolution`
    // by post-processing.
    deps_with_versions.sort();
    LockfilePackage {
        name: p.name.clone(),
        version: p.version.to_string(),
        source: p.source_url.clone(),
        hash: p.hash.clone(),
        provenance_hash: p.provenance_hash.clone(),
        dependencies: deps_with_versions,
    }
}

fn escape_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out
}

/// Post-process `dependencies = [name version]` strings so that they
/// reference the resolved version. Called after the constructor
/// (which initially populates name-only entries from `direct_deps`).
///
/// This is a public helper for the CLI to invoke after `from_resolution`
/// — keeps the resolver layer free of the "version stringification"
/// concern.
pub fn rewrite_dep_strings(lock: &mut Lockfile) {
    let resolved: BTreeMap<String, String> = lock
        .packages
        .iter()
        .map(|p| (p.name.clone(), p.version.clone()))
        .collect();

    for pkg in &mut lock.packages {
        let mut new_deps = Vec::with_capacity(pkg.dependencies.len());
        for dep in &pkg.dependencies {
            // dep is currently a bare name; rewrite to "name version"
            // if we know the resolved version.
            if let Some(v) = resolved.get(dep) {
                new_deps.push(format!("{dep} {v}"));
            } else {
                new_deps.push(dep.clone());
            }
        }
        new_deps.sort();
        pkg.dependencies = new_deps;
    }
}

/// Save the lockfile to `path`. Atomic: writes to `<path>.tmp` then renames.
pub fn save(lock: &Lockfile, path: &std::path::Path) -> Result<(), PkgError> {
    let bytes = lock.to_canonical_toml();
    let tmp = path.with_extension("lock.tmp");
    std::fs::write(&tmp, bytes.as_bytes())
        .map_err(|e| PkgError::Io(format!("write {}: {e}", tmp.display())))?;
    std::fs::rename(&tmp, path).map_err(|e| {
        PkgError::Io(format!(
            "rename {} → {}: {e}",
            tmp.display(),
            path.display()
        ))
    })?;
    Ok(())
}

/// Load a lockfile from `path`.
pub fn load(path: &std::path::Path) -> Result<Lockfile, PkgError> {
    let s = std::fs::read_to_string(path)
        .map_err(|e| PkgError::Io(format!("read {}: {e}", path.display())))?;
    Lockfile::parse_str(&s)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;
    use crate::resolver::ResolvedPackage;
    use semver::Version;
    use std::collections::BTreeMap;

    fn fake_root() -> ResolvedPackage {
        ResolvedPackage {
            name: "main".into(),
            version: Version::new(0, 1, 0),
            source_url: "path+file:///tmp/main".into(),
            hash: "blake3:root".into(),
            provenance_hash: None,
            dependency_names: vec!["alpha".into(), "beta".into()],
            local_path: "/tmp/main".into(),
        }
    }

    fn fake_pkg(name: &str, ver: (u64, u64, u64), deps: &[&str], hash: &str) -> ResolvedPackage {
        ResolvedPackage {
            name: name.into(),
            version: Version::new(ver.0, ver.1, ver.2),
            source_url: format!("path+file:///tmp/{name}"),
            hash: hash.into(),
            provenance_hash: None,
            dependency_names: deps.iter().map(|s| (*s).to_string()).collect(),
            local_path: format!("/tmp/{name}").into(),
        }
    }

    fn manifest_minimal() -> Manifest {
        Manifest::parse_str(
            "[package]\nname = \"main\"\nversion = \"0.1.0\"\ncobrust-version = \"0.0.1\"\n[bin]\nname = \"main\"\npath = \"src/main.cb\"\n",
        )
        .unwrap()
    }

    #[test]
    fn build_and_serialize_minimal() {
        let m = manifest_minimal();
        let mut packages = BTreeMap::new();
        packages.insert(
            "alpha".into(),
            fake_pkg("alpha", (1, 0, 0), &[], "blake3:abc1"),
        );
        packages.insert(
            "beta".into(),
            fake_pkg("beta", (2, 1, 0), &["alpha"], "blake3:abc2"),
        );
        let res = Resolution {
            root: fake_root(),
            packages,
        };
        let mut lock = Lockfile::from_resolution(&m, &res).unwrap();
        rewrite_dep_strings(&mut lock);

        let s = lock.to_canonical_toml();
        // Sorted by (name, version): alpha < beta < main
        let p_alpha = s.find("name = \"alpha\"").unwrap();
        let p_beta = s.find("name = \"beta\"").unwrap();
        let p_main = s.find("name = \"main\"").unwrap();
        assert!(p_alpha < p_beta);
        assert!(p_beta < p_main);

        // beta's dependencies should include "alpha 1.0.0"
        assert!(s.contains("\"alpha 1.0.0\""));

        // Round-trip parse.
        let lock2 = Lockfile::parse_str(&s).unwrap();
        assert_eq!(lock, lock2);
    }

    #[test]
    fn determinism_under_dep_permutation() {
        let m = manifest_minimal();
        let mk_lock = |order: &[(&str, &str, &[&str])]| {
            let mut packages = BTreeMap::new();
            for (n, _, deps) in order {
                packages.insert(
                    (*n).to_string(),
                    fake_pkg(n, (1, 0, 0), deps, &format!("blake3:{n}")),
                );
            }
            let mut lock = Lockfile::from_resolution(
                &m,
                &Resolution {
                    root: fake_root(),
                    packages,
                },
            )
            .unwrap();
            rewrite_dep_strings(&mut lock);
            lock.to_canonical_toml()
        };

        let order_a: &[(&str, &str, &[&str])] = &[
            ("z", "1.0.0", &["a"]),
            ("a", "1.0.0", &[]),
            ("m", "1.0.0", &["z", "a"]),
        ];
        let order_b: &[(&str, &str, &[&str])] = &[
            ("a", "1.0.0", &[]),
            ("m", "1.0.0", &["a", "z"]),
            ("z", "1.0.0", &["a"]),
        ];
        assert_eq!(mk_lock(order_a), mk_lock(order_b));
    }

    #[test]
    fn parse_round_trip() {
        let lock = Lockfile {
            metadata: LockfileMetadata {
                manifest_hash: "blake3:beef".into(),
                lockfile_version: LOCKFILE_VERSION,
            },
            packages: vec![
                LockfilePackage {
                    name: "a".into(),
                    version: "1.0.0".into(),
                    source: "path+file:///tmp/a".into(),
                    hash: "blake3:aaa".into(),
                    provenance_hash: None,
                    dependencies: vec![],
                },
                LockfilePackage {
                    name: "b".into(),
                    version: "2.0.0".into(),
                    source: "path+file:///tmp/b".into(),
                    hash: "blake3:bbb".into(),
                    provenance_hash: Some("blake3:prov".into()),
                    dependencies: vec!["a 1.0.0".into()],
                },
            ],
        };
        let s = lock.to_canonical_toml();
        let parsed = Lockfile::parse_str(&s).unwrap();
        assert_eq!(parsed, lock);
    }

    #[test]
    fn rejects_incompatible_version() {
        let s = "[metadata]\nmanifest_hash = \"blake3:x\"\nlockfile_version = 999\n";
        let err = Lockfile::parse_str(s).unwrap_err();
        assert!(matches!(
            err,
            PkgError::Lockfile(LockfileError::IncompatibleVersion { .. })
        ));
    }

    #[test]
    fn verify_manifest_hash_succeeds_and_fails() {
        let m = manifest_minimal();
        let lock = Lockfile {
            metadata: LockfileMetadata {
                manifest_hash: m.manifest_hash(),
                lockfile_version: LOCKFILE_VERSION,
            },
            packages: vec![],
        };
        lock.verify_manifest_hash(&m).unwrap();

        let mismatched = Lockfile {
            metadata: LockfileMetadata {
                manifest_hash: "blake3:wrong".into(),
                lockfile_version: LOCKFILE_VERSION,
            },
            packages: vec![],
        };
        assert!(mismatched.verify_manifest_hash(&m).is_err());
    }

    #[test]
    fn canonical_has_lf_and_trailing_state() {
        let lock = Lockfile {
            metadata: LockfileMetadata {
                manifest_hash: "blake3:x".into(),
                lockfile_version: LOCKFILE_VERSION,
            },
            packages: vec![],
        };
        let s = lock.to_canonical_toml();
        assert!(!s.contains('\r'));
        // Last line must end with \n.
        assert!(s.ends_with('\n'));
    }

    #[test]
    fn save_and_load_round_trip() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("cobrust.lock");
        let lock = Lockfile {
            metadata: LockfileMetadata {
                manifest_hash: "blake3:hash".into(),
                lockfile_version: LOCKFILE_VERSION,
            },
            packages: vec![LockfilePackage {
                name: "a".into(),
                version: "1.0.0".into(),
                source: "path+file:///x".into(),
                hash: "blake3:a".into(),
                provenance_hash: None,
                dependencies: vec![],
            }],
        };
        save(&lock, &path).unwrap();
        let loaded = load(&path).unwrap();
        assert_eq!(loaded, lock);
    }
}
