// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Translated by cobrust-translator (synthetic-LLM mode).
// source-library: click 8.1.7
// oracle: cpython 3.11 (module: click)
// functions translated: 16 (Command + OptionSpec + ArgumentSpec builders + run dispatcher)
// see PROVENANCE.toml for the full manifest.

//! Cobrust translation of `click` 8.1.7 (ADR-0022 ecosystem batch).
//!
//! Generated by `cobrust-translator` in synthetic-LLM mode; see
//! `PROVENANCE.toml` for the full manifest and `corpus/click/README.md`
//! for the ADR-0022 scope window.
//!
//! This is the M-batch deliverable per ADR-0022 §1 — the second
//! ecosystem-breadth crate translating Python's `click` CLI parsing
//! library. The translation pattern (per ADR-0022 §3) maps click's
//! decorator-heavy Python DSL (`@click.command`, `@click.option`,
//! `@click.argument`) to a fluent Rust builder API that internally
//! wires through `clap = "4"` for the actual parse.
//!
//! Decorator-translation table (per ADR-0022 §3):
//! - `@click.command(name=..., help=...)` → `Command::new(name).about(help)`
//! - `@click.option('--flag', type=int, default=0, help=...)` →
//!   `OptionSpec::new('--flag').type_(ParamType::Int).default('0').help(...)`
//! - `@click.argument('NAME', type=str)` → `ArgumentSpec::new('NAME').type_(ParamType::Str)`
//! - `command(argv)` (the click runtime) → `Command::run(argv)` returning `RunResult`
//!
//! Public surface:
//! - `Command::new(name)` + `.about(help)` + `.option(opt)` + `.argument(arg)` + `.run(argv)`
//! - `OptionSpec::new(long)` fluent: `.short / .type_ / .default / .help / .required`
//! - `ArgumentSpec::new(name)` fluent: `.type_ / .optional`
//! - `RunResult` with `.option(name)` / `.argument(name)` accessors
//! - `ClickError { kind, message }` single error type

// Fluent-builder Self-return pattern is pervasive in this crate; pedantic
// `must_use_candidate` would require ~10 attributes for ergonomic builders
// the user is already chaining. The decorator-chain compiler is necessarily
// long. Both are accepted at module level; mirrors cobrust-coil's pattern.
#![allow(clippy::must_use_candidate)]
#![allow(clippy::too_many_lines)]

mod decorators;

pub use crate::decorators::{
    ArgumentSpec, ClickError, ClickErrorKind, Command, OptionSpec, ParamType, RunResult,
};

#[cfg(feature = "pyo3")]
mod pyo3_bindings;

#[cfg(feature = "pyo3")]
pub use pyo3_bindings::*;
