// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Translated by cobrust-translator (synthetic-LLM mode).
// source-library: tomli 2.0.1
// oracle: cpython 3.11 (module: tomllib)
// functions translated: 12
// see PROVENANCE.toml for the full manifest.

//! Cobrust translation of `tomli` 2.0.1.
//!
//! Generated by `cobrust-translator` in synthetic-LLM mode. The
//! provenance manifest at `PROVENANCE.toml` records every input that
//! drove this translation.
//!
//! M4 scope window: see `corpus/tomli/README.md` §"Scope window".
//!
//! Public surface:
//! - `loads(src: &str) -> Result<Value, TomliError>` — parse a TOML string.
//! - `Value` — heterogeneous TOML value tree.
//! - `TomliError` — single error type.
//! - `to_json` / `table_to_json` — JSON conversion helpers used by the L3 differential gate.

mod parser;

pub use crate::parser::{TomliError, Value, loads, table_to_json, to_json};
