// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Translated by cobrust-translator (synthetic-LLM mode).
// source-library: numpy 2.0.2
// oracle: cpython 3.11 (module: numpy)
//   + M7.2 indexing per ADR-0015 + M7.3 reductions per ADR-0016 + M7.4 linalg per ADR-0017
//   + M7.5 random per ADR-0018.
// functions translated: 51 (M7.0..M7.3 = 36; M7.4: matmul, dot, det, solve, inv, svd, eigh,
//   cholesky; M7.5: default_rng, seed, integers, random, normal, uniform, choice).
// see PROVENANCE.toml for the full manifest.

//! Cobrust translation of NumPy 2.0.2 — M7.0 ndarray foundation +
//! M7.1 ufuncs/broadcasting + M7.2 indexing + M7.3 reductions +
//! M7.4 linalg + M7.5 random.
//!
//! Generated by `cobrust-translator` in synthetic-LLM mode; see
//! `PROVENANCE.toml` for the full manifest and
//! `corpus/numpy/M7.{0,1,2,3,4,5}/README.md` for each sub-milestone scope.
//!
//! M7.0 (per ADR-0012 + ADR-0013) lands ndarray foundation: closed
//! dtype tier, tagged-union `Array`, four constructors. M7.1 (per
//! ADR-0014) lands ufuncs (binary + comparison + unary math),
//! broadcasting per numpy rules, type promotion per NEP 50, typed
//! constructors, nested-list parsing. M7.2 (per ADR-0015) lands
//! indexing (basic slicing, integer-array, boolean masks),
//! `np.where`, and view-vs-copy semantics via `ArrayView<'a>` /
//! `ArrayViewMut<'a>`. M7.3 (per ADR-0016) lands reductions: nine
//! ops (`sum / prod / mean / std / var / min / max / argmin /
//! argmax`) with `axis: Option<i64>`; pairwise summation for
//! floats; ddof for std/var; numpy-exact empty-array semantics.
//! M7.4 (per ADR-0017) lands linalg: 8 ops (`matmul / dot / det /
//! solve / inv / svd / eigh / cholesky`) with float-only inputs
//! and `rtol=1e-6` agreement on cond ≤ 100 matrices.
//! M7.5 (per ADR-0018) lands random: `Generator` newtype struct over
//! `rand_pcg::Pcg64`; `default_rng` / `seed` / `integers` / `random` /
//! `normal` / `uniform` / `choice`; KS-test acceptance gate vs numpy
//! 2.0.2 (p > 0.01) for continuous distributions; seed-reproducibility
//! within Cobrust across runs of the same binary.
//!
//! Public surface (M7.0 + M7.1 + M7.2 + M7.3 + M7.4 + M7.5):
//! - `Array` — closed tagged-union over `ndarray::ArrayD<T>` for the
//!   five M7.0 dtypes per ADR-0013 §4.
//! - `Dtype` — closed enum (`Int32 | Int64 | Float32 | Float64 |
//!   Bool`); `from_python_string`, `to_python_string`, `item_size`.
//! - Constructors: `array(values, shape, dtype)`,
//!   `zeros(shape, dtype)`, `ones(shape, dtype)`,
//!   `arange(start, stop, step, dtype)`,
//!   `array_i32 / array_i64 / array_f32 / array_f64 / array_bool`,
//!   `array_from_nested(NestedList, dtype)`.
//! - Ufuncs: `Array::add / sub / mul / div / pow` (binary math),
//!   `Array::eq_ / ne_ / lt / le / gt / ge` (comparison; result is
//!   `Dtype::Bool`), `Array::sin / cos / exp / log / sqrt`
//!   (element-wise math).
//! - `result_type(a, b) -> Dtype` — NumPy 2.x NEP 50 promotion.
//! - `broadcast_shape(&[usize], &[usize]) -> Result<Vec<usize>>` — numpy
//!   broadcasting shape computation.
//! - `Array::shape() / ndim() / size() / dtype() / repr() / to_json()`
//!   — observers.
//! - **M7.2** — `Index` enum, `SliceSpec`, `Array::slice` /
//!   `slice_mut` (basic slicing → view), `Array::take` /
//!   `Array::mask` (advanced indexing → copy), `Array::index_get`
//!   (top-level multi-axis dispatcher), `np_where(cond, x, y)`,
//!   `ArrayView<'a>` / `ArrayViewMut<'a>` (closed enums per dtype).
//! - **M7.3** — `sum / prod / mean / std / var / min / max /
//!   argmin / argmax` (free functions and `Array::*` methods);
//!   `pairwise_sum_f32 / f64` helpers; `axis: Option<i64>`
//!   parameter; `ddof: u32` for std/var.
//! - **M7.4** — `matmul / dot / det / solve / inv / svd / eigh /
//!   cholesky` (free functions; `Array::matmul` and `Array::dot`
//!   methods); `SvdResult` / `EighResult` structs; float-only
//!   contract; pure-Rust kernels (opt-in `linalg-backend`
//!   feature for `ndarray-linalg`).
//! - **M7.5** — `Generator` newtype struct over `rand_pcg::Pcg64`;
//!   `default_rng(seed)`; `Generator::seed / integers / random /
//!   normal / uniform / choice`; same Cobrust seed → identical
//!   stream across runs.
//! - `NumpyError` / `NumpyErrorKind` — closed error taxonomy.

mod aggregates;
mod array;
mod broadcast;
mod broadcast_extra;
// #145 numpy gap-closure BATCH 3 — the unary TRANSCENDENTAL elementwise
// ufunc family (`exp`/`log`/`log10`/`sqrt`/`sin`/`cos`/`tan` + optional
// `exp2`/`log2`/`cbrt`/`sinh`/`cosh`/`tanh`), 1-arg Buffer -> Buffer
// FLOAT-returning ops wired EXACTLY like the BATCH-2 manipulate reshape
// ops (borrow-Buffer-arg → fresh-Buffer-return). Int/bool inputs promote
// to Float64; Float32 stays Float32; Float64 stays Float64.
// + #145 BATCH 4 — the unary ROUNDING / SIGN family (`abs`/`floor`/
// `ceil`/`round`/`trunc`/`square`/`sign`), SAME 1-arg Buffer -> Buffer
// shape but DTYPE-PRESERVING (int->int, f32->f32, f64->f64; floor/ceil/
// round/trunc are int no-ops). `round` is round-half-to-EVEN (banker's);
// `sign(0)=0` + `sign(NaN)=NaN`.
mod elementwise;
// ADR-0072 8/8 first proof — `.cb`-side C-ABI shims for the
// `coil.Buffer` opaque handle (the EIGHTH and final cobra-batch
// ecosystem module — completes the workspace-vendored ecosystem chain).
// Pure value-handle pattern (no callbacks): three constructors
// (`zeros`/`ones`/`eye`) + one read method (`print_buffer`). Operator
// dispatch (`a + b`) + index dispatch (`a[i]`) are explicitly deferred
// to a sub-ADR per ADR-0072 §"coil deep operator/index".
//
// Stream W P0 增量 (2026-05-29) extends the surface with 8 free
// functions (mgrid/ogrid/broadcast_to/mean/median/std/var/split)
// composed from the existing reduce + constructors machinery.
pub mod cabi;
mod constructors;
mod dtype;
mod error;
mod grid;
mod index;
mod linalg;
mod manipulate;
mod print;
mod promote;
mod random;
mod reduce;
mod ufunc;
mod view;

pub use crate::aggregates::{
    mean_scalar, median_scalar, split_first_chunk, std_scalar, var_scalar,
};
pub use crate::array::Array;
pub use crate::broadcast::broadcast_shape;
pub use crate::broadcast_extra::broadcast_to_1d;
pub use crate::constructors::{
    LinspaceResult, NestedList, arange, arange_count, array, array_bool, array_f32, array_f64,
    array_from_nested, array_i32, array_i64, diag, eye, full, linspace, logspace, ones, tri, tril,
    triu, zeros,
};
pub use crate::dtype::{Dtype, FloatInfo, FloatKind, IntInfo, IntKind, finfo, iinfo};
pub use crate::elementwise::{
    // #145 BATCH 4 — DTYPE-PRESERVING rounding / sign family. None of
    // these clash with a `ufunc` re-export, so they re-export flat.
    abs,
    // #145 BATCH 15 — the 2-Buffer FLOAT ufuncs (`(Array, Array) -> Array`,
    // float-PROMOTING). None clash with a `ufunc` re-export, so flat.
    arctan2,
    cbrt,
    ceil,
    cosh,
    exp2,
    floor,
    hypot,
    log2,
    log10,
    logaddexp,
    round,
    sign,
    sinh,
    square,
    tanh,
    trunc,
    // NOTE: `exp` / `log` / `sin` / `cos` / `sqrt` are also re-exported
    // from `ufunc` (the `Result`-returning `Array::*` method backers);
    // the `elementwise` versions are the infallible `Array -> Array`
    // cabi-shim backers. They live under the `elementwise` path
    // (`elementwise::exp`) to avoid the name clash — see `cabi.rs`.
};
pub use crate::error::{NumpyError, NumpyErrorKind};
pub use crate::grid::{mgrid_1d, ogrid_1d};
pub use crate::index::{Index, SliceSpec, index_get, np_where};
pub use crate::linalg::{EighResult, SvdResult, cholesky, det, dot, eigh, inv, matmul, solve, svd};
pub use crate::manipulate::{
    concatenate, diff, flatten, flip, hstack, ravel, repeat, roll, tile, transpose, vstack,
};
pub use crate::print::array_repr;
pub use crate::promote::{result_type, unary_math_dtype};
pub use crate::random::{Generator, default_rng};
pub use crate::reduce::{
    argmax, argmin, max, mean, min, pairwise_sum_f32, pairwise_sum_f64, prod, std, sum, var,
};
pub use crate::ufunc::{
    add, cos, div, eq, exp, ge, gt, iscomplex, isinf, isnan, isreal, le, log, lt, mul, ne, pow,
    sin, sqrt, sub,
};
pub use crate::view::{ArrayView, ArrayViewMut};

#[cfg(feature = "pyo3")]
mod pyo3_bindings;

#[cfg(feature = "pyo3")]
pub use pyo3_bindings::*;
