// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Translated by cobrust-translator (synthetic-LLM mode).
// source-library: msgpack 1.0.8
// oracle: cpython 3.11 (module: msgpack)
// functions translated: 19 (17 pure-Python + 2 Cython-typed)
// see PROVENANCE.toml for the full manifest.

//! Cobrust translation of `msgpack-python` 1.0.8 (M6 native-ext scope window).
//!
//! Generated by `cobrust-translator` in synthetic-LLM mode; see
//! `PROVENANCE.toml` for the full manifest and `corpus/msgpack/README.md`
//! for the M6 scope window.
//!
//! This is the M6 milestone deliverable per constitution §7 — the
//! first library with a native extension successfully translated to
//! Cobrust. The pure-Python `fallback.py` and the Cython
//! `_packer.pyx` / `_unpacker.pyx` sources both produce
//! byte-identical output for every input in the M6 scope.
//!
//! Public surface:
//! - `pack(value: &MsgValue, out: &mut Vec<u8>) -> Result<(), MsgError>` — encode.
//! - `pack_to_vec(value: &MsgValue) -> Result<Vec<u8>, MsgError>` — encode owned.
//! - `unpack(data: &[u8]) -> Result<MsgValue, MsgError>` — decode.
//! - `MsgValue` — heterogeneous value tree (nil/bool/int/float/str/bytes/array/map).
//! - `MsgError` / `MsgErrorKind` — single error type.

mod parser;

pub use crate::parser::{
    MsgError, MsgErrorKind, MsgValue, pack, pack_array, pack_bin, pack_float, pack_int, pack_map,
    pack_str, pack_to_vec, pack_uint, pack_uint_cython, unpack, unpack_array, unpack_bin,
    unpack_float, unpack_int, unpack_map, unpack_one, unpack_str, unpack_uint, unpack_uint_cython,
};

#[cfg(feature = "pyo3")]
mod pyo3_bindings;

#[cfg(feature = "pyo3")]
pub use pyo3_bindings::*;
