// AUTO-GENERATED by T1.1 (real-LLM full-library translation).
// source-library: tomli 2.0.1
// oracle: cpython 3.11 (module: tomllib)
// translator: cobrust-translator::build_translation_prompt_rich
// provider: user_codex_t1_1 (gpt-5.5)
// see docs/agent/findings/0.1.0-beta-tomli-full-translation.md.

//! Translated parser body — produced via real-LLM end-to-end.
//! Each emitted block carries its own per-function provenance comment.

#![allow(clippy::missing_errors_doc, clippy::missing_panics_doc)]

use std::collections::BTreeMap;
use std::fmt;

/// Heterogeneous TOML value. Subset per M4 scope window
/// (see corpus/tomli/README.md).
#[derive(Clone, Debug, PartialEq)]
pub enum Value {
    /// Boolean.
    Bool(bool),
    /// 64-bit signed integer.
    Int(i64),
    /// UTF-8 string.
    Str(String),
    /// Heterogeneous array.
    Array(Vec<Value>),
    /// Nested table.
    Table(BTreeMap<String, Value>),
}

/// Single error type for tomli parse failures.
#[derive(Clone, Debug)]
pub struct TomliError {
    /// Human-readable message.
    pub message: String,
    /// Byte offset of the error in the source.
    pub pos: usize,
}

impl fmt::Display for TomliError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "tomli error at byte {}: {}", self.pos, self.message)
    }
}

impl std::error::Error for TomliError {}

/// Maximum nesting depth for TOML values (arrays / inline tables).
/// Exceeding this limit returns `TomliError` instead of overflowing the
/// call stack on adversarial input (B4 / P1 stack-OOM fix).
pub const MAX_DEPTH: u32 = 100;

impl TomliError {
    pub fn new(message: impl Into<String>, pos: usize) -> Self {
        Self {
            message: message.into(),
            pos,
        }
    }

    /// Returned when nesting depth exceeds [`MAX_DEPTH`].
    #[must_use]
    pub fn too_deep(pos: usize) -> Self {
        Self {
            message: format!(
                "nesting depth exceeds maximum ({MAX_DEPTH}); possible adversarial input"
            ),
            pos,
        }
    }
}

/// Cursor over the input source.
pub struct State<'a> {
    pub src: &'a str,
    pub bytes: &'a [u8],
    pub pos: usize,
    /// Current recursion depth for nested value parsing.
    /// Incremented when entering `parse_array` / `parse_inline_table`;
    /// checked against [`MAX_DEPTH`] to prevent stack overflow on
    /// adversarial deeply-nested input (B4 fix).
    pub depth: u32,
}

impl<'a> State<'a> {
    pub fn new(src: &'a str) -> Self {
        Self {
            src,
            bytes: src.as_bytes(),
            pos: 0,
            depth: 0,
        }
    }

    pub fn eof(&self) -> bool {
        self.pos >= self.bytes.len()
    }

    pub fn peek(&self) -> Option<u8> {
        self.bytes.get(self.pos).copied()
    }

    pub fn advance(&mut self) -> Option<u8> {
        let b = self.peek();
        if b.is_some() {
            self.pos += 1;
        }
        b
    }

    pub fn expect(&mut self, ch: u8) -> Result<(), TomliError> {
        if self.peek() == Some(ch) {
            self.pos += 1;
            Ok(())
        } else {
            Err(TomliError::new(
                format!("expected {:?}", char::from(ch)),
                self.pos,
            ))
        }
    }
}

/// Walk into the table at `path`, creating intermediate tables.
fn ensure_path<'a>(
    root: &'a mut BTreeMap<String, Value>,
    path: &[String],
) -> Result<&'a mut BTreeMap<String, Value>, TomliError> {
    let mut cursor: &'a mut BTreeMap<String, Value> = root;
    for part in path {
        let entry = cursor
            .entry(part.clone())
            .or_insert_with(|| Value::Table(BTreeMap::new()));
        cursor = match entry {
            Value::Table(t) => t,
            _ => {
                return Err(TomliError::new(
                    format!("path conflicts with non-table at {part:?}"),
                    0,
                ));
            }
        };
    }
    Ok(cursor)
}

/// Convert a parsed value to its serde_json representation. Used by
/// the L3 differential gate to compare against CPython's
/// `tomllib.loads()` output.
#[must_use]
pub fn to_json(value: &Value) -> serde_json::Value {
    match value {
        Value::Bool(b) => serde_json::Value::Bool(*b),
        Value::Int(i) => serde_json::Value::Number(serde_json::Number::from(*i)),
        Value::Str(s) => serde_json::Value::String(s.clone()),
        Value::Array(arr) => serde_json::Value::Array(arr.iter().map(to_json).collect()),
        Value::Table(t) => {
            let mut m = serde_json::Map::new();
            for (k, v) in t {
                m.insert(k.clone(), to_json(v));
            }
            serde_json::Value::Object(m)
        }
    }
}

/// Convert a top-level table to a JSON object.
#[must_use]
pub fn table_to_json(t: &BTreeMap<String, Value>) -> serde_json::Value {
    let mut m = serde_json::Map::new();
    for (k, v) in t {
        m.insert(k.clone(), to_json(v));
    }
    serde_json::Value::Object(m)
}

// ---- LLM-emitted function bodies (verbatim per fn) ----

// fn:loads provider=user_codex_t1_1 model=gpt-5.5 cache_hit=false prompt_tokens=1972 completion_tokens=587
pub fn loads(src: &str) -> Result<BTreeMap<String, Value>, TomliError> {
    let mut state = State::new(src);
    let mut root = BTreeMap::new();
    let mut current_path = Vec::new();

    loop {
        skip_whitespace(&mut state);

        if state.eof() {
            return Ok(root);
        }

        if state.peek() == Some(b'[') {
            let parts = parse_table_header(&mut state)?;
            ensure_path(&mut root, &parts)?;
            current_path = parts;
        } else {
            let current = ensure_path(&mut root, &current_path)?;
            parse_kv(&mut state, current)?;
        }
    }
}

// fn:parse_array provider=user_codex_t1_1 model=gpt-5.5 cache_hit=false prompt_tokens=1960 completion_tokens=574
// B4 fix: depth-guarded entry point.
fn parse_array(state: &mut State<'_>) -> Result<Vec<Value>, TomliError> {
    state.depth += 1;
    if state.depth > MAX_DEPTH {
        return Err(TomliError::too_deep(state.pos));
    }
    let result = parse_array_inner(state);
    state.depth -= 1;
    result
}

fn parse_array_inner(state: &mut State<'_>) -> Result<Vec<Value>, TomliError> {
    state.expect(b'[')?;
    let mut out = Vec::new();

    skip_whitespace(state);
    if state.peek() == Some(b']') {
        state.pos += 1;
        return Ok(out);
    }

    loop {
        out.push(parse_value(state)?);
        skip_whitespace(state);

        match state.peek() {
            Some(b',') => {
                state.pos += 1;
                skip_whitespace(state);
                if state.peek() == Some(b']') {
                    state.pos += 1;
                    return Ok(out);
                }
            }
            Some(b']') => {
                state.pos += 1;
                return Ok(out);
            }
            _ => return Err(TomliError::new("expected , or ]", state.pos)),
        }
    }
}

// fn:parse_basic_string provider=user_codex_t1_1 model=gpt-5.5 cache_hit=false prompt_tokens=1857 completion_tokens=1344
fn parse_basic_string(state: &mut State<'_>) -> Result<String, TomliError> {
    state.expect(b'"')?;
    let mut out = Vec::new();

    while let Some(ch) = state.advance() {
        if ch == b'"' {
            return match String::from_utf8(out) {
                Ok(value) => Ok(value),
                Err(_) => Err(TomliError::new("invalid utf-8 string", state.pos)),
            };
        }

        if ch == b'\\' {
            if state.eof() {
                return Err(TomliError::new("unterminated escape", state.pos));
            }

            let Some(esc) = state.advance() else {
                return Err(TomliError::new("unterminated escape", state.pos));
            };

            match esc {
                b'n' => out.push(b'\n'),
                b't' => out.push(b'\t'),
                b'\\' => out.push(b'\\'),
                b'"' => out.push(b'"'),
                b'r' => out.push(b'\r'),
                _ => {
                    let esc_ch = char::from(esc);
                    return Err(TomliError::new(format!("bad escape \\{esc_ch}"), state.pos));
                }
            }
        } else {
            out.push(ch);
        }
    }

    Err(TomliError::new("unterminated string", state.pos))
}

// fn:parse_bool provider=user_codex_t1_1 model=gpt-5.5 cache_hit=false prompt_tokens=1886 completion_tokens=638
fn parse_bool(state: &mut State<'_>) -> Result<bool, TomliError> {
    let Some(rest) = state.bytes.get(state.pos..) else {
        return Err(TomliError::new("expected bool", state.pos));
    };

    if rest.starts_with(b"true") {
        state.pos += 4;
        return Ok(true);
    }

    if rest.starts_with(b"false") {
        state.pos += 5;
        return Ok(false);
    }

    Err(TomliError::new("expected bool", state.pos))
}

// fn:parse_inline_table provider=user_codex_t1_1 model=gpt-5.5 cache_hit=false prompt_tokens=2005 completion_tokens=658
// B4 fix: depth-guarded entry point.
fn parse_inline_table(state: &mut State<'_>) -> Result<BTreeMap<String, Value>, TomliError> {
    state.depth += 1;
    if state.depth > MAX_DEPTH {
        return Err(TomliError::too_deep(state.pos));
    }
    let result = parse_inline_table_inner(state);
    state.depth -= 1;
    result
}

fn parse_inline_table_inner(state: &mut State<'_>) -> Result<BTreeMap<String, Value>, TomliError> {
    state.expect(b'{')?;
    let mut out = BTreeMap::new();
    skip_whitespace(state);

    if state.peek() == Some(b'}') {
        state.pos += 1;
        return Ok(out);
    }

    loop {
        let key = parse_key(state)?;
        skip_whitespace(state);
        state.expect(b'=')?;
        let value = parse_value(state)?;
        out.insert(key, value);
        skip_whitespace(state);

        match state.peek() {
            Some(b',') => {
                state.pos += 1;
                skip_whitespace(state);
                if state.peek() == Some(b'}') {
                    return Err(TomliError::new("trailing comma in inline table", state.pos));
                }
            }
            Some(b'}') => {
                state.pos += 1;
                return Ok(out);
            }
            _ => return Err(TomliError::new("expected , or }", state.pos)),
        }
    }
}

// fn:parse_int provider=user_codex_t1_1 model=gpt-5.5 cache_hit=false prompt_tokens=1914 completion_tokens=682
fn parse_int(state: &mut State<'_>) -> Result<i64, TomliError> {
    let start = state.pos;

    if matches!(state.peek(), Some(b'-' | b'+')) {
        state.pos += 1;
    }

    let digits_start = state.pos;
    while matches!(state.peek(), Some(b) if b.is_ascii_digit()) {
        state.pos += 1;
    }

    if state.pos == digits_start {
        Err(TomliError::new("expected digit", state.pos))
    } else {
        match state.src[start..state.pos].parse::<i64>() {
            Ok(value) => Ok(value),
            Err(_) => Err(TomliError::new("invalid integer", state.pos)),
        }
    }
}

// fn:parse_key provider=user_codex_t1_1 model=gpt-5.5 cache_hit=false prompt_tokens=1950 completion_tokens=403
fn parse_key(state: &mut State<'_>) -> Result<String, TomliError> {
    skip_whitespace(state);
    let start = state.pos;

    while let Some(b) = state.peek() {
        if b.is_ascii_alphanumeric() || matches!(b, b'_' | b'-') {
            state.pos += 1;
        } else {
            break;
        }
    }

    if state.pos == start {
        return Err(TomliError::new("expected key", state.pos));
    }

    Ok(state.src[start..state.pos].to_string())
}

// fn:parse_kv provider=user_codex_t1_1 model=gpt-5.5 cache_hit=false prompt_tokens=1862 completion_tokens=576
fn parse_kv(state: &mut State<'_>, dest: &mut BTreeMap<String, Value>) -> Result<(), TomliError> {
    let key = parse_key(state)?;
    skip_whitespace(state);
    state.expect(b'=')?;
    let value = parse_value(state)?;
    let _old_value = dest.insert(key, value);
    Ok(())
}

// fn:parse_literal_string provider=user_codex_t1_1 model=gpt-5.5 cache_hit=false prompt_tokens=1866 completion_tokens=331
fn parse_literal_string(state: &mut State<'_>) -> Result<String, TomliError> {
    state.expect(b'\'')?;
    let mut out = String::new();
    while let Some(b) = state.advance() {
        if b == b'\'' {
            return Ok(out);
        }
        out.push(char::from(b));
    }
    Err(TomliError::new("unterminated literal string", state.pos))
}

// fn:parse_table_header provider=user_codex_t1_1 model=gpt-5.5 cache_hit=false prompt_tokens=1893 completion_tokens=207
fn parse_table_header(state: &mut State<'_>) -> Result<Vec<String>, TomliError> {
    state.expect(b'[')?;

    let mut parts = Vec::new();
    parts.push(parse_key(state)?);

    while state.peek() == Some(b'.') {
        state.pos += 1;
        parts.push(parse_key(state)?);
    }

    skip_whitespace(state);
    state.expect(b']')?;

    Ok(parts)
}

// fn:parse_value provider=user_codex_t1_1 model=gpt-5.5 cache_hit=false prompt_tokens=1964 completion_tokens=763
fn parse_value(state: &mut State<'_>) -> Result<Value, TomliError> {
    skip_whitespace(state);
    match state.peek() {
        Some(b'"') => parse_basic_string(state).map(Value::Str),
        Some(b'\'') => parse_literal_string(state).map(Value::Str),
        Some(b'[') => parse_array(state).map(Value::Array),
        Some(b'{') => parse_inline_table(state).map(Value::Table),
        Some(b't' | b'f') => parse_bool(state).map(Value::Bool),
        Some(b'-' | b'+' | b'0'..=b'9') => parse_int(state).map(Value::Int),
        Some(ch) => {
            let pos = state.pos;
            let ch = char::from(ch);
            Err(TomliError::new(
                format!("unexpected character {ch:?} at pos {pos}"),
                pos,
            ))
        }
        None => {
            let pos = state.pos;
            Err(TomliError::new(
                format!("unexpected character None at pos {pos}"),
                pos,
            ))
        }
    }
}

// fn:skip_whitespace provider=user_codex_t1_1 model=gpt-5.5 cache_hit=false prompt_tokens=1897 completion_tokens=312
fn skip_whitespace(state: &mut State<'_>) {
    while let Some(ch) = state.peek() {
        match ch {
            b' ' | b'\t' | b'\n' | b'\r' => {
                state.pos += 1;
            }
            b'#' => {
                while let Some(comment_ch) = state.peek() {
                    if comment_ch == b'\n' {
                        break;
                    }
                    state.pos += 1;
                }
            }
            _ => return,
        }
    }
}
