// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Translated by cobrust-translator (synthetic-LLM mode).
// source-library: requests 2.31.0
// oracle: cpython 3.11 (module: requests)
// functions translated: 13 (6 free verbs + Session::new + 6 Session methods)
// see PROVENANCE.toml for the full manifest.

//! Cobrust translation of `requests` 2.31.0 (ADR-0022 ecosystem batch).
//!
//! Generated by `cobrust-translator` in synthetic-LLM mode; see
//! `PROVENANCE.toml` for the full manifest and `corpus/requests/README.md`
//! for the ADR-0022 scope window.
//!
//! This is the M-batch deliverable per ADR-0022 §1 — the first
//! ecosystem-breadth crate translating Python's `requests` HTTP client
//! surface. The translation pattern is "translate the surface, bind the
//! core" (per ADR-0012); the Rust backend is `reqwest::blocking` so the
//! public surface stays synchronous, honouring constitution §2.2 ("no
//! async / sync coloring"). The Cobrust structured-concurrency runtime
//! (per ADR-0019 Phase E) lands at M8+; until then the surface stays
//! sync and the backend can be swapped without a public-API break.
//!
//! Public surface:
//! - Free verb functions: `get / post / put / patch / delete / head`.
//! - Stateful client: `Session::new()` + the same six verb methods.
//! - `Response` with `.status_code() / .ok() / .headers() / .text() / .json()`.
//! - Single error type: `HttpError { kind, message }`.

mod client;

pub use crate::client::{
    HttpError, HttpErrorKind, HttpMethod, Response, Session, delete, get, head, patch, post, put,
};

#[cfg(feature = "pyo3")]
mod pyo3_bindings;

#[cfg(feature = "pyo3")]
pub use pyo3_bindings::*;
