[[cases]]
input = "3 4\n1 3 5 7\n10 11 16 20\n23 30 34 60\n3\n"
expected_stdout = "true\n"
expected_exit_code = 0

[[cases]]
input = "3 4\n1 3 5 7\n10 11 16 20\n23 30 34 60\n13\n"
expected_stdout = "false\n"
expected_exit_code = 0

[[cases]]
input = "1 1\n1\n1\n"
expected_stdout = "true\n"
expected_exit_code = 0

[[cases]]
input = "2 3\n1 4 7\n10 13 16\n10\n"
expected_stdout = "true\n"
expected_exit_code = 0

[[cases]]
input = "2 3\n1 4 7\n10 13 16\n9\n"
expected_stdout = "false\n"
expected_exit_code = 0
