[[cases]]
input = "[]\n"
expected_stdout = "1\n"
expected_exit_code = 0

[[cases]]
input = "[[]]\n"
expected_stdout = "2\n"
expected_exit_code = 0

[[cases]]
input = "[[][]]\n"
expected_stdout = "3\n"
expected_exit_code = 0

[[cases]]
input = "[[]][]\n"
expected_stdout = "3\n"
expected_exit_code = 0

[[cases]]
input = "[[[]]]\n"
expected_stdout = "4\n"
expected_exit_code = 0
