// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Translated by cobrust-translator (synthetic-LLM mode).
// source-library: dateutil 2.9.0.post0
// oracle: cpython 3.11 (module: dateutil)
// functions translated: 8
// see PROVENANCE.toml for the full manifest.

//! Cobrust translation of `dateutil` 2.9.0.post0 (M5 scope window).
//!
//! Generated by `cobrust-translator` in synthetic-LLM mode; see
//! `PROVENANCE.toml` for the full manifest and `corpus/dateutil/README.md`
//! for the M5 scope window.
//!
//! Public surface:
//! - `parse_iso(src: &str) -> Result<DateTuple, ParserError>` — strict ISO-8601.
//! - `relativedelta_add(...)` — pure-arithmetic relative-delta addition.
//! - `DateTuple` — element-wise mirror of the Python 9-tuple.
//! - `ParserError` — single error type for parse failures.

mod parser;

pub use crate::parser::{
    DateTuple, ParserError, days_in_month, is_digit, is_leap_year, normalize_datetime, parse_iso,
    relativedelta_add,
};

#[cfg(feature = "pyo3")]
mod pyo3_bindings;

#[cfg(feature = "pyo3")]
pub use pyo3_bindings::*;
