// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Translated by cobrust-translator (synthetic-LLM mode).
// source-library: numpy 2.0.2
// oracle: cpython 3.11 (module: numpy)
// scope: M7.0 ndarray foundation per ADR-0013 + M7.1 ufuncs/broadcasting per ADR-0014.
// functions translated: 19 (M7.0: array, zeros, ones, arange, parse_dtype, shape_size,
//   cast_to_dtype, array_repr; M7.1: add, sub, mul, div, pow, sin, cos, exp, log, sqrt,
//   plus result_type / broadcast_shape internals).
// see PROVENANCE.toml for the full manifest.

//! Cobrust translation of NumPy 2.0.2 — M7.0 ndarray foundation +
//! M7.1 ufuncs/broadcasting.
//!
//! Generated by `cobrust-translator` in synthetic-LLM mode; see
//! `PROVENANCE.toml` for the full manifest and
//! `corpus/numpy/M7.{0,1}/README.md` for each sub-milestone scope.
//!
//! M7.0 (per ADR-0012 + ADR-0013) lands ndarray foundation: closed
//! dtype tier, tagged-union `Array`, four constructors. M7.1 (per
//! ADR-0014) lands ufuncs (binary + comparison + unary math),
//! broadcasting per numpy rules, type promotion per NEP 50, typed
//! constructors, nested-list parsing.
//!
//! Public surface (M7.0 + M7.1):
//! - `Array` — closed tagged-union over `ndarray::ArrayD<T>` for the
//!   five M7.0 dtypes per ADR-0013 §4.
//! - `Dtype` — closed enum (`Int32 | Int64 | Float32 | Float64 |
//!   Bool`); `from_python_string`, `to_python_string`, `item_size`.
//! - Constructors: `array(values, shape, dtype)`,
//!   `zeros(shape, dtype)`, `ones(shape, dtype)`,
//!   `arange(start, stop, step, dtype)`,
//!   `array_i32 / array_i64 / array_f32 / array_f64 / array_bool`,
//!   `array_from_nested(NestedList, dtype)`.
//! - Ufuncs: `Array::add / sub / mul / div / pow` (binary math),
//!   `Array::eq_ / ne_ / lt / le / gt / ge` (comparison; result is
//!   `Dtype::Bool`), `Array::sin / cos / exp / log / sqrt`
//!   (element-wise math).
//! - `result_type(a, b) -> Dtype` — NumPy 2.x NEP 50 promotion.
//! - `broadcast_shape(&[usize], &[usize]) -> Result<Vec<usize>>` — numpy
//!   broadcasting shape computation.
//! - `Array::shape() / ndim() / size() / dtype() / repr() / to_json()`
//!   — observers.
//! - `NumpyError` / `NumpyErrorKind` — closed error taxonomy.

mod array;
mod broadcast;
mod constructors;
mod dtype;
mod error;
mod print;
mod promote;
mod ufunc;

pub use crate::array::Array;
pub use crate::broadcast::broadcast_shape;
pub use crate::constructors::{
    NestedList, arange, arange_count, array, array_bool, array_f32, array_f64, array_from_nested,
    array_i32, array_i64, ones, zeros,
};
pub use crate::dtype::Dtype;
pub use crate::error::{NumpyError, NumpyErrorKind};
pub use crate::print::array_repr;
pub use crate::promote::{result_type, unary_math_dtype};
pub use crate::ufunc::{add, cos, div, eq, exp, ge, gt, le, log, lt, mul, ne, pow, sin, sqrt, sub};

#[cfg(feature = "pyo3")]
mod pyo3_bindings;

#[cfg(feature = "pyo3")]
pub use pyo3_bindings::*;
