// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Translated by cobrust-translator (synthetic-LLM mode).
// source-library: numpy 2.0.2
// oracle: cpython 3.11 (module: numpy)
// scope: M7.0 ndarray foundation per ADR-0013
// functions translated: 7 (array, zeros, ones, arange, plus parse_dtype + array_repr + shape_size helpers)
// see PROVENANCE.toml for the full manifest.

//! Cobrust translation of NumPy 2.0.2 — M7.0 ndarray foundation.
//!
//! Generated by `cobrust-translator` in synthetic-LLM mode; see
//! `PROVENANCE.toml` for the full manifest and `corpus/numpy/M7.0/README.md`
//! for the M7.0 scope window.
//!
//! This is the M7.0 sub-milestone deliverable per ADR-0012 + ADR-0013.
//! The ndarray crate (https://crates.io/crates/ndarray, version 0.16)
//! provides the storage backend; cobrust-numpy owns the Python-shaped
//! contract (dtype string parsing, error taxonomy, `numpy.array(...)`
//! / `numpy.zeros(...)` / `numpy.ones(...)` / `numpy.arange(...)`
//! constructors).
//!
//! Public surface (M7.0):
//! - `Array` — closed tagged-union over `ndarray::ArrayD<T>` for the
//!   five M7.0 dtypes per ADR-0013 §4.
//! - `Dtype` — closed enum (`Int32 | Int64 | Float32 | Float64 |
//!   Bool`); `from_python_string`, `to_python_string`, `item_size`.
//! - `array(values, shape, dtype)` — flat-buffer construction.
//! - `zeros(shape, dtype)` — zero-fill.
//! - `ones(shape, dtype)` — one-fill.
//! - `arange(start, stop, step, dtype)` — half-open range.
//! - `Array::shape() / ndim() / size() / dtype() / repr() / to_json()`
//!   — observers.
//! - `NumpyError` / `NumpyErrorKind` — closed error taxonomy.

mod array;
mod constructors;
mod dtype;
mod error;
mod print;

pub use crate::array::Array;
pub use crate::constructors::{arange, arange_count, array, ones, zeros};
pub use crate::dtype::Dtype;
pub use crate::error::{NumpyError, NumpyErrorKind};
pub use crate::print::array_repr;

#[cfg(feature = "pyo3")]
mod pyo3_bindings;

#[cfg(feature = "pyo3")]
pub use pyo3_bindings::*;
