// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Translated by cobrust-translator (synthetic-LLM mode).
// source-library: CPython sqlite3 (PEP 249 DB-API 2.0)
// oracle: cpython 3.11 (module: sqlite3)
// see PROVENANCE.toml for the full manifest.

//! Cobrust translation of CPython's `sqlite3` (PEP 249 DB-API 2.0)
//! surface — v0.7.0 Stream Z.7.c.
//!
//! Generated by `cobrust-translator` in synthetic-LLM mode; see
//! `PROVENANCE.toml` for the full manifest and the roadmap
//! `docs/agent/strategy/v0.7.0-network-backend-libraries-roadmap.md`
//! §4.1 (the sqlite3 row + §5 MUST-ship DB connector).
//!
//! This is the v0.7.0 Stream Z.7.c deliverable: the one MUST-ship DB
//! connector. The translation pattern is "translate the surface, bind
//! the core" (per ADR-0012); the Rust backend is `rusqlite` (bundled
//! libsqlite3 — no system library needed). The public surface stays
//! sync, honouring constitution §2.2 ("no async / sync coloring") and
//! matching Python's `sqlite3`, which is itself sync (roadmap Z-Q4).
//!
//! LLM-first (constitution §2.5): the surface mirrors the canonical
//! Python priors —
//! `sqlite3.connect(":memory:").cursor().execute(sql, params)
//! .fetchall()` — so an LLM agent writes it correctly on the first try.
//!
//! # Example
//!
//! (Marked `ignore`, not run as a doctest: the bare `[lib] name = "den"` — required
//! for the PyO3 `den` module — trips Rust 1.94 merged-doctests' rlib resolution on a
//! clean build. The same code paths are compile-run-verified by the integration suite
//! `tests/sqlite3_downstream.rs`. See docs/agent/findings/f62-*.md.)
//!
//! ```ignore
//! use den::{connect, Value, MEMORY};
//!
//! let conn = connect(MEMORY).expect("open in-memory db");
//! let mut cur = conn.cursor();
//! cur.execute("CREATE TABLE t (id INTEGER PRIMARY KEY, name TEXT)", &[])
//!     .expect("create");
//! cur.execute(
//!     "INSERT INTO t (name) VALUES (?)",
//!     &[Value::Text("ada".to_owned())],
//! )
//! .expect("insert");
//! cur.execute("SELECT id, name FROM t", &[]).expect("select");
//! let rows = cur.fetchall();
//! assert_eq!(rows.len(), 1);
//! assert_eq!(rows[0].get(1), Some(&Value::Text("ada".to_owned())));
//! ```
//!
//! Public surface:
//! - `connect(path) -> Result<Connection, SqliteError>` (`":memory:"`
//!   via the [`MEMORY`] constant, or a file path).
//! - [`Connection`]: `.cursor()`, `.execute(sql)`,
//!   `.execute_params(sql, params)`, `.commit()`, `.rollback()`,
//!   `.close()`.
//! - [`Cursor`]: `.execute(sql, params)`, `.fetchone()`,
//!   `.fetchmany(n)`, `.fetchall()`, `.rowcount()`, `.lastrowid()`,
//!   and `Iterator` over [`Row`].
//! - [`Value`]: the five SQLite storage classes
//!   (NULL/INTEGER/REAL/TEXT/BLOB).
//! - [`Row`]: positional cell access.
//! - [`SqliteError`] / [`SqliteErrorKind`]: closed error taxonomy
//!   (constitution §2.2 — `Result<T, E>`, never exceptions).

pub mod cabi;
mod connection;
mod error;
mod value;

pub use crate::connection::{Connection, Cursor, MEMORY, connect};
pub use crate::error::{SqliteError, SqliteErrorKind};
pub use crate::value::{Row, Value};

#[cfg(feature = "pyo3")]
mod pyo3_bindings;

#[cfg(feature = "pyo3")]
pub use pyo3_bindings::*;
