// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Translated by cobrust-translator (synthetic-LLM mode).
// source-library: flask 3.0 (web-server surface)
// oracle: cpython 3.11 (module: flask)
// see PROVENANCE.toml for the full manifest.

//! Cobrust translation of Flask 3.0's sync web-server surface —
//! v0.7.0 Stream Z.1.a. The Cobrust module name is `pit` (ADR-0071:
//! "a snake pit handles many callers"); the *source* library is
//! `flask` (kept distinct per the rebrand provenance rule).
//!
//! Generated by `cobrust-translator` in synthetic-LLM mode; see
//! `PROVENANCE.toml` for the full manifest and the roadmap
//! `docs/agent/strategy/v0.7.0-network-backend-libraries-roadmap.md`
//! §4.1 (the flask row: TRANSLATE L0-L3 surface, axum backend,
//! sync-style via `task::block_on`) + §5 (MUST-ship HTTP server).
//!
//! The translation pattern is "translate the surface, bind the core"
//! (per ADR-0012); the Rust backend is `axum`/`tokio`. The public
//! surface stays SYNC — `App::run` bridges to a singleton tokio runtime
//! via `Runtime::block_on` (ADR-0028 §A precedent), honouring
//! constitution §2.2 ("no async / sync coloring" at the user layer).
//!
//! LLM-first (constitution §2.5, per ADR-0071 §3): the API *shape*
//! mirrors Flask exactly — register a route, return a text or JSON
//! response, read the request — so an LLM agent writes it correctly on
//! the first try (maximize-overlap-with-training-data). Errors are a
//! closed, exhaustively-matchable `Result` taxonomy
//! (compile-time-catch-errors). The one shape divergence in this
//! increment: routes are registered through a method API
//! (`app.get(path, handler)`) rather than the `@app.route` decorator,
//! which lands with the `.cb`-source wiring follow-on.
//!
//! # Example
//!
//! (Marked `ignore`, not run as a doctest: the bare `[lib] name = "pit"` — required
//! for the PyO3 `pit` module — trips Rust 1.94 merged-doctests' rlib resolution on a
//! clean build. The same code paths are compile-run-verified by the integration suite
//! `tests/pit_downstream.rs`. See `docs/agent/findings/f62-*.md`.)
//!
//! ```ignore
//! use pit::{App, Request, Response};
//! use serde_json::json;
//!
//! let mut app = App::new();
//! app.get("/", |_req: Request| Response::text("hello, pit"))
//!     .expect("register /");
//! app.get("/users/<id>", |req: Request| {
//!     let id = req.path_param("id").unwrap_or("?");
//!     Response::json(&json!({ "id": id }))
//! })
//! .expect("register /users/<id>");
//! app.post("/echo", |req: Request| {
//!     Response::text(req.text().unwrap_or_default())
//! })
//! .expect("register /echo");
//!
//! // Blocks the calling thread, serving until killed:
//! app.run("127.0.0.1", 8080).expect("serve");
//! ```
//!
//! Public surface:
//! - [`App`]: `new()`, `route(method, path, handler)`,
//!   `get/post/put/delete(path, handler)`, `run(host, port)` (blocking),
//!   `serve_in_background(host, port)` (test/embedding harness).
//! - [`Request`]: `method`, `path`, `path_param(name)`, `query(name)`,
//!   `header(name)`, `body`, `text`, `json`.
//! - [`Response`]: `text(body)`, `json(value)`, `from_parts(...)`,
//!   `with_status` / `with_header` builders, `status_code` / `headers`
//!   / `body` observers.
//! - [`Handler`]: `Arc<dyn Fn(Request) -> Response + Send + Sync>`.
//! - [`PitError`] / [`PitErrorKind`]: closed error taxonomy
//!   (constitution §2.2 — `Result<T, E>`, never exceptions).

mod app;
mod error;
mod request;
mod response;
mod routing;

pub use crate::app::{App, Handler, MAX_BODY_BYTES, ServerHandle};
pub use crate::error::{PitError, PitErrorKind};
pub use crate::request::Request;
pub use crate::response::Response;

#[cfg(feature = "pyo3")]
mod pyo3_bindings;

#[cfg(feature = "pyo3")]
pub use pyo3_bindings::*;
